### ISSUE TITLE
Too bright

### ISSUE THREAD

**Issue by Diztend** [bradleyq/1_16_shaders#10]
The lighting seems too bright. 
It is even bright at night
At daytime the sky is also bright

**Comment by Reeses-Puffs** [comment]
I'm pretty sure this is a stylistic choice

**Comment by bradleyq** [comment]
^

**Comment by bradleyq** [comment]
you can tweak the autoexposure if you have any experience with shaders but I don't have the capacity to give specific help.

**Comment by bradleyq** [comment]
https://github.com/bradleyq/mc_vanilla_shaders/issues/12
