### ISSUE TITLE
Looking at a bright scene causes the shader to trigger the F3+A "flashbang" effect

### ISSUE THREAD

**Issue by CalXee** [bradleyq/1_16_shaders#12]
While I now know from my previous report that the effect is meant to trigger when pressing F3+A, it also triggers when looking at a bright scene from a dark scene (or joining a world with a bright scene) in general, which is quite obstructive. I don't think this is intended.

https://www.youtube.com/watch?v=7UsqYKn_mtQ

**Comment by bradleyq** [comment]
intended. It is the auto-exposure effect.

**Comment by bradleyq** [comment]
for those of you who want to reduce the exposure target, on line 36 in exposure_apply.fsh:
    `OutTexel.rgb /= 2.0 * clamp(exposure,0.2,1.0)` increase the `2.0` to your liking.

**Comment by CalXee** [comment]
Alternatively, one can change 0.2 and 1.0 to be identical numbers in ``clamp(exposure,0.2,1.0)`` to completely disable the auto exposure, and render the game at a consistent brightness. Janky solution, but it seems to work.
