### ISSUE TITLE
Water is rendered very prominently in front of fog

### ISSUE THREAD

**Issue by CalXee** [bradleyq/1_16_shaders#13]
Not sure if this existed in 1.16, but I reproduced it in 1.17.

**Comment by CalXee** [comment]
![2021-06-17_11 06 00](https://user-images.githubusercontent.com/68349758/122423748-2636d280-cf5c-11eb-932b-44c2d6002556.png)
![2021-06-17_11 07 47](https://user-images.githubusercontent.com/68349758/122424020-626a3300-cf5c-11eb-8d1d-cde94ae1a091.png)

**Comment by bradleyq** [comment]
looks like a bug however 1.17 is not supported atm.

**Comment by bradleyq** [comment]
this will no longer be a problem in 1.17 since the entire shader is being rewritten. closing.
