### ISSUE TITLE
Compiling Error with Texture2D on dev branch sometimes

### ISSUE THREAD

**Issue by blank3times** [bradleyq/1_16_shaders#17]
I've used the 1.16 version without problems, but the 1.19 dev version fails to load with the errors
```OpenGL debug message: id=0, source=SHADER COMPILER, type=ERROR, severity=HIGH, message='SHADER_ID_COMPILE error has been generated. GLSL compile failed for shader 33, "": ERROR: 0:254: 'function' : is removed in Forward Compatible context texture2D
ERROR: 0:254: 'texture2D' : no matching overloaded function found (using implicit conversion) 
ERROR: 0:254: 'texture2D' : function is not known 
ERROR: 0:254: 'r' : field selection requires structure, vector, or matrix on left hand side 

'
```
I've also gotten the texture2D errors on DartCat's fabulous shaders, but I dismissed them until I see this pack is in development still.

I assume this isn't a problem for everybody because otherwise you would have been unable to do other development on the pack.

**Comment by Godlander** [comment]
pretty sure this is because your hardware doesn't support older versions of glsl.
i think the older version is being used because of `gl_NormalMatrix`? It seems the 1.19 dev rp isn't using core shaders, which i believe are neccesary to pass in that data in newer version since that gl built in doesnt exist anymore

**Comment by blank3times** [comment]
I see a core shaders folder whose contents get modified in the dev rp. I did dismiss the other case as being from an old pack. I suppose that's an interesting change.

I thought I pasted it in for the original error report, but I got a message along the lines of forward compatibility (matching your theory), I'll try to find and paste that now. On the bright side, with the shader reload mod I get a cool entity effect (I assume with data) from before it's able to be passed into the in-that-case nonexistent post shaders.

**Comment by blank3times** [comment]
'function' : is removed in Forward Compatible context texture2D

**Comment by bradleyq** [comment]
ah that's my bad. I am still in the process of upgrading to core 150. there are still some texture2D calls lying around. Nvidia is pretty lax when it comes to this.

**Comment by bradleyq** [comment]
should be resolved as of [9e2f49c](https://github.com/bradleyq/mc_vanilla_shaders/commit/9e2f49cb234c8c7f570b53524b73b8c7d4a83b9b). let me know if it is fixed and I will close.

**Comment by bradleyq** [comment]
@blank3times

**Comment by blank3times** [comment]
Time to crash my computerrrrrrrrrrrrrrrrrrrrrr

**Comment by blank3times** [comment]
Thank you! It loaded in the menu. I think I can close it if it loads in a world as well?

**Comment by blank3times** [comment]
It's beautiful and I'm surprised I have more than 2 fps since I'm not using sodium for obvious reasons. This stuff is magic, thank you for fixing!

**Comment by blank3times** [comment]
@bradleyq I don't know if you can see this since I haven't properly used github in the past, but I'm curious about version 330 and what's new (and/or optimized) about it (besides that mac won't support it), because I saw in that commit large deletions and large additions besides just changing the number. =]

Thanks again for removing Texture2D, it was a blast exploring the area I was in with the pack on!

Update: You can tell I am not used to github because I accidentally pressed the reopen button (oops, heh heh) O_O

**Comment by bradleyq** [comment]
@blank3times 330 itself does not give too much of an improvement. Maybe 1fps. I needed to upgrade for new GLSL api func  floatBitsToUint. This lets me store depth buffer info into a texture to sidestep this bug: https://bugs.mojang.com/browse/MC-254044

I also needed to reshuffle and add some passes to fix this, hence the deletions.

**Comment by blank3times** [comment]
That's a helpful change. Thanks for the info! =] For optimization I thought maybe just making the code easier to write not playing fps, but I'm glad you can circumvent the bug which I would vote for if I had Mojira. Glad I'm not a mac user, heh heh.
