### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by AlecMcCutcheon** [bradleyq/1_16_shaders#18]
What setting in the config files do I need to change to increase/decrease the amount of reflections on the water

**Comment by bradleyq** [comment]
there is no configuration for this in any version. I don't plan to add support for this in the future either. If you are using r2.3 or r.25, you caon do it manually:
assets/minecraft/shaders/program/composite2.fsh line 60. You can reduce ```SpecTmp.a``` by multiplying it by a small value like ```0.5```.

**Comment by AlecMcCutcheon** [comment]
That's actually what I meant I knew there wasn't a easy to change configuration, could u also tell be which to find the variable for bloom?

**Comment by bradleyq** [comment]
shaders/program/bloom.fsh, modify `bloomAccumulator *= 1.5;`
