### ISSUE TITLE
adjusting block light color

### ISSUE THREAD

**Issue by yubato** [bradleyq/1_16_shaders#19]
I want to set block light in the dev version to be more white/closer to vanilla instead of yellow. Are there any variables I can adjust?

**Comment by bradleyq** [comment]
shaders/include/light.glsl
line 26: vec4(1.2, 0.80, 0.45, 1.0)
Change this to whatever color you want.

**Comment by blank3times** [comment]
Is that rgba or hsva? The x is greater than 1 so how does that work? ^-^

**Comment by bradleyq** [comment]
rgba. As it is right now there is some clipping since MC only supports RGBA8 output. I will probably change this later when I introduce HDR using some hacks.

**Comment by blank3times** [comment]
Thank you!
