### ISSUE TITLE
Whenever I take damage the screen flashes white

### ISSUE THREAD

**Issue by ChiefArug** [bradleyq/1_16_shaders#21]
The slight delay is just from server ping
Video: https://github.com/bradleyq/mc_vanilla_shaders/assets/73862885/1836f39f-32a1-4113-aae0-a63662d6571c (not sure why its not embedding)
Using 1.20 with version 3.0 (<https://github.com/bradleyq/mc_vanilla_shaders/releases/tag/v3.0>)

**Comment by bradleyq** [comment]
should be resolved in 3.0.1
