### ISSUE TITLE
Shadow are bugged when sun is in the back of the player

### ISSUE THREAD

**Issue by vadim-soude** [bradleyq/1_16_shaders#24]
https://youtu.be/rODXspblOoE 

Here's the video of the issues, if you look of the left and right bottom corner of the screen you can notice some shadows are not supposed to act like that.

Minecraft version : 1.19.4 (tested in 1.20.1 and the bug is also present)

**Comment by Godlander** [comment]
i think thats working as intended
vanilla doesn't have a shadow map texture or similar
to get "correct" shadows u'd have to voxelize the entire world, and even that's subject to frustum culling
i think the shadows here are done in screen-space, so only objects visible on screen can cast shadows. thats why the shadows on the edges of screen may be inaccurate

**Comment by bradleyq** [comment]
See @Godlander's comment. Closed.
