### ISSUE TITLE
I don't understand if I'm doing something wrong...

### ISSUE THREAD

**Issue by KriperoNio** [bradleyq/1_16_shaders#25]
I don't understand if I'm doing something wrong, I just installed vanilla minecraft and connected shaders with a resource pack, and with completely blurred combinations...and it just turns out something very nauseating.
![image](https://github.com/bradleyq/mc_vanilla_shaders/assets/75113283/2a77bd65-c550-41ce-ae4d-c7a957d7afcb)
![2023-11-10_15-36-42](https://github.com/bradleyq/mc_vanilla_shaders/assets/75113283/ebcb720c-71fd-448b-a3f6-7f950fbba231)
![2023-11-10_15-36-52](https://github.com/bradleyq/mc_vanilla_shaders/assets/75113283/97e0947a-87c1-49ac-8e56-d7f36a89cf7c)
![2023-11-10_15-37-07](https://github.com/bradleyq/mc_vanilla_shaders/assets/75113283/a8ce1378-dc1e-4ea6-8e46-80efb55f43ca)

help please

**Comment by KriperoNio** [comment]
I just want to make a map without mods, but it needs an amazing shader like yours. And the problem is that obj mc does not work with non-vanilla shaders, textures are not displayed.)

**Comment by blank3times** [comment]
Looks like you don't have fabulous graphics turned on, you need graphics set to fabulous for the rendering to redraw itself properly. (Found in video settings)

**Comment by KriperoNio** [comment]
YES it helped) THANK YOU! And I wanted to warn you, I found the bug right away... when you put a block the shadow is rendered incorrectly here's a look:
thanks again)
![2023-11-11_08-13-05](https://github.com/bradleyq/mc_vanilla_shaders/assets/75113283/1a92bbba-eb24-4252-b494-fab5ff07f2bd)
![2023-11-11_08-13-24](https://github.com/bradleyq/mc_vanilla_shaders/assets/75113283/fd6f56f3-d640-41c6-9afe-7fa70ec8f31b)
![2023-11-11_08-13-39](https://github.com/bradleyq/mc_vanilla_shaders/assets/75113283/cfcb36d5-fd71-4b22-899a-05a494d0d74f)

**Comment by KriperoNio** [comment]
You just need to turn on awesome graphics:
Settings -> Graphics settings -> Graphics: Awesome!
A very cool shader!
