### ISSUE TITLE
Rendering Issue with Lodestone/Malum/Core Shaders

### ISSUE THREAD

**Issue by emoace** [bradleyq/1_16_shaders#26]
![2024-01-19_11 12 13](https://github.com/bradleyq/mc_vanilla_shaders/assets/77821109/44253c35-cf35-4738-b4fd-fb9babb1f7cd)

Hi it seems when I use Ether and Core Shaders from the Malum mod that all that renders is a green box. I'm using the 1.20 dev branch but this also happens with v3.0.1

Any idea of what could be causing this? I know Core Shaders are a bit wonky sometimes.

**Comment by Godlander** [comment]
resourcepack shaders have many incompatibilities with mods. you should use vanilla minecraft with this resourcepack

**Comment by bradleyq** [comment]
As godlander says. Use version < 3.0 like 2 or 2.5 if you want to better compatibility with mods that add additional shader effects.
