### ISSUE TITLE
Shaders incompatible with Sodium

### ISSUE THREAD

**Issue by LightningFerix** [bradleyq/1_16_shaders#29]
Hi, I was wondering if the incompatibility with Sodium is a known issue. I understand that you are trying to build this shader without requiring mods, but Sodium is a really common performance mod, so the incompatibility is pretty rough. It makes the world look like this:

![2024-08-27_18 14 50](https://github.com/user-attachments/assets/5a7d38a3-58bb-4fef-bda7-c15415c76e70)

**Comment by Godlander** [comment]
its sodium that chose to not support a vanilla resourcepack feature in order to save performance

so having compatibility would mean removing most of sodium's performance gains, so you should just use the vanilla game

**Comment by LightningFerix** [comment]
Ah, okay, appreciate the explanation. Thank you for your time! Still love your work :)
