### ISSUE TITLE
"Resource reload failed" on Linux

### ISSUE THREAD

**Issue by pajicadvance** [bradleyq/1_16_shaders#3]
Trying to load the shaders.zip resource pack with Fabulous graphics on fails with the message "Resource reload failed":

![2020-09-15_17-44](https://user-images.githubusercontent.com/32738446/93233478-68d44000-f77b-11ea-9f23-6f8faf97a42d.png)

Crash log: https://paste.ee/p/8V8Er

The resource pack works without any issues on Windows with the exact same Minecraft installation.

Specs:

![2020-09-15_17-48](https://user-images.githubusercontent.com/32738446/93233951-fa43b200-f77b-11ea-8780-8f61f5abf6ad.png)

Using Mesa 20.1.7.

**Comment by nift4** [comment]
Same issue on Debian / Wayland - Mesa 20.1.8 but with vanilla 1.16.3

**Comment by nift4** [comment]
fixed version to test @pajicadvance 
[shader.zip](https://github.com/bradleyq/1_16_shaders/files/5283305/shader.zip)

**Comment by pajicadvance** [comment]
Yep, this works. That was a surprisingly easy fix. Thanks for figuring it out @nift4 .

**Comment by bradleyq** [comment]
removing texture2dLod. It doesn't seem to work anyway.

**Comment by nift4** [comment]
stonks ;)
