### ISSUE TITLE
Reflections still move unnaturally when view bobbing is turned on or when jumping

### ISSUE THREAD

**Issue by CalXee** [bradleyq/1_16_shaders#7]
Some of the reflections on the side of the screen still moves strangely when jumping or walking with view bobbing on.

**Comment by Reeses-Puffs** [comment]
could not replicate

**Comment by bradleyq** [comment]
this is intended, only one of three is possible in SSR:
- disable reflections on edge of screen
- white / sky colored reflection at edge
- wobbly. I chose this one...
