### ISSUE TITLE
Adjust exposure?

### ISSUE THREAD

**Issue by THECRUSTIEST** [bradleyq/1_16_shaders#9]
I like this shader a lot, but it feels like the brightness is too high, even when set to "Moody". For example, sand appears *very* white in most conditions. Is there any way to reduce the exposure or the magnitude of bloom effects? Thanks!

**Comment by Reeses-Puffs** [comment]
the only way to do this is to edit the files themselves. as previously stated in the comments in #1, shader config may become possible in the caves and cliffs update with the updated shader system.

**Comment by bradleyq** [comment]
dupe of https://github.com/bradleyq/mc_vanilla_shaders/issues/12
